set number
set expandtab
set tabstop=2
set shiftwidth=2
set softtabstop=2
syntax on
"set spell spelllang=en_us
set listchars=trail:·,precedes:«,extends:»,eol:↲,tab:▸\ 
set list
au BufReadCmd *.love call zip#Browse(expand("<amatch>"))
